---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-${USER_NAME}
  namespace: ${USER_NAME}
spec:
  instances: ${POSTGRES_INSTANCES}
  imageName: "${POSTGRES_DEFAULT_IMAGE}"

  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:
    synchronous:
      method: any
      number: 1
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:
      - host replication all all trust
      - hostssl replication all all trust
      - hostssl replication streaming_replica all cert
      - host all all 0.0.0.0/0 md5

  storage:
    size: ${POSTGRES_STORAGE}
  walStorage:
    size: ${POSTGRES_WAL_STORAGE}
  
  # Scheduling: Ensure pods spread across your 3 disks/nodes
  affinity:
    nodeSelector:
      node.workshop/role: postgres
    podAntiAffinityType: required # Strict: won't start 2 pods on 1 node
    topologyKey: kubernetes.io/hostname

  resources:
    requests:
      memory: "${POSTGRES_MEMORY}"
      cpu: "${POSTGRES_CPU}"
    limits:
      memory: "${POSTGRES_MAX_MEMORY}"
      cpu: "${POSTGRES_MAX_CPU}"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-cluster-${USER_NAME}
  namespace: ${USER_NAME}
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": cnpg-cluster-${USER_NAME}
  podMetricsEndpoints:
  - port: metrics
