apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cnpg-cluster-${USER_NAME}-backup
  namespace: ${USER_NAME}
spec:
  cluster:
    name: cnpg-cluster-${USER_NAME}
  target: "primary"
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io